name: mlpipe_env
dependencies:
  - python=3.6
  - pip

  # conda dependencies for dev & examples
  - anaconda-client
  - conda-build
  - pillow
  - pytest
  - numba
  - redis

  - pip:
    # pip dependencies that are required by the mlpipe-trainer package
    - tensorflow==2.0.0-beta1
    - namedlist==1.7
    - h5py==2.9.*
    - numpy==1.16.*
    - pymongo==3.7.*
    - requests==2.21.*

    # pip dependencies for dev & examples
    - opencv-python
    - mkdocs
    - setuptools
    - twine
    - tqdm
    - redis # this is the python interface for redis
